name: Deploy to ECS

on:
  workflow_call:
    secrets:
      AWS_REGION:
        required: true
      AWS_ROLE_TO_ASSUME:
        required: true
      ECS_CLUSTER:
        required: true
      ECS_SERVICE:
        required: true
      TASK_DEF_FILE:
        required: true
      ECR_REPO:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Construct image URI
        id: compute
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI="${ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:${IMAGE_TAG}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Replace image URI in ECS task definition
        run: |
          sed -i "s|<IMAGE_URI>|$IMAGE_URI|g" Infrastructure/${{ secrets.TASK_DEF_FILE }}

      - name: Register new ECS task definition
        id: task-def
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://Infrastructure/${{ secrets.TASK_DEF_FILE }} \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
