name: Frontend Dev CI/CD

on:
  push:
    branches:
      - dev

# Required for OIDC authentication with AWS
permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run Tests and Notify
    uses: ./.github/workflows/deploy-test-and-notify-for-dev.yml

  build:
    name: Build & Push Docker Image
    needs: test
    uses: ./.github/workflows/deploy-build-and-push-for-dev.yml

  deploy:
    name: Deploy to ECS (Dev)
    needs: build
    uses: ./.github/workflows/deploy-ecs-for-dev.yml
    with:
      image_uri: ${{ needs.build.outputs.image_uri }}
