name: Frontend Dev CI/CD

on:
  push:
    branches:
      - dev

jobs:
  test:
    uses: ./.github/workflows/test-and-notify.yml

  build:
    needs: test
    uses: ./.github/workflows/build-and-push.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-ecs.yml
    with:
      image_uri: ${{ needs.build.outputs.image_uri }}
